// src/shared/components/ui/Toast/Toast.solid.tsx
/**
 * @fileoverview Toast Solid Component
 * @description Solid.js implementation of Toast notification
 */

import { mergeProps, splitProps, onCleanup, type Component } from 'solid-js';
import { globalTimerManager } from '@/shared/utils/timer-management';
import styles from './Toast.module.css';

export interface ToastItem {
  id: string;
  type: 'info' | 'success' | 'warning' | 'error';
  title: string;
  message: string;
  duration?: number;
  actionText?: string;
  onAction?: () => void;
}

export interface ToastProps {
  toast: ToastItem;
  onRemove: (id: string) => void;
  className?: string;
  role?: 'alert' | 'status';
  'aria-label'?: string;
  'data-testid'?: string;
}

/**
 * Toast component - displays a notification message
 */
export const Toast: Component<ToastProps> = props => {
  const merged = mergeProps({ role: 'alert' as const }, props);
  const [local, ariaProps, rest] = splitProps(
    merged,
    ['toast', 'onRemove', 'className', 'role'],
    ['aria-label', 'data-testid']
  );

  // Auto-dismiss timer with cleanup
  if (local.toast?.duration && local.toast.duration > 0) {
    const timer = globalTimerManager.setTimeout(() => {
      local.onRemove?.(local.toast?.id ?? '');
    }, local.toast.duration);

    onCleanup(() => {
      globalTimerManager.clearTimeout(timer);
    });
  }

  const handleClose = (e: MouseEvent | KeyboardEvent) => {
    e.preventDefault();
    local.onRemove?.(local.toast?.id ?? '');
  };

  const handleAction = (e: MouseEvent | KeyboardEvent) => {
    e.preventDefault();
    if (local.toast?.onAction) {
      local.toast.onAction();
    }
    local.onRemove?.(local.toast?.id ?? '');
  };

  const toastClass = () => {
    const classes = [styles.toast, styles[`toast--${local.toast.type}`]];
    if (local.className) {
      classes.push(local.className);
    }
    return classes.filter(Boolean).join(' ');
  };

  return (
    <div class={toastClass()} role={local.role} {...ariaProps} {...rest}>
      <div class={styles['toast__content']}>
        <div class={styles['toast__header']}>
          <span class={styles['toast__title']}>{local.toast.title}</span>
          <button
            type='button'
            class={styles['toast__close']}
            onClick={handleClose}
            aria-label='Close notification'
          >
            ×
          </button>
        </div>
        <div class={styles['toast__message']}>{local.toast.message}</div>
        {local.toast.actionText && (
          <div class={styles['toast__actions']}>
            <button
              type='button'
              class={styles['toast__action']}
              onClick={handleAction}
              aria-label={local.toast.actionText}
            >
              {local.toast.actionText}
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

// src/shared/components/ui/Toast/Toast.tsx
import { getPreactSignals, getPreactHooks } from '@shared/utils/external';
import styles from '@shared/components/ui/Toast/Toast.module.css';

const { signal } = getPreactSignals();
const { useEffect } = getPreactHooks();

// Constants
const DEFAULT_TOAST_DURATION = 5000; // 5 seconds

export interface ToastItem {
  id: string;
  type: 'info' | 'warning' | 'error' | 'success';
  title: string;
  message: string;
  duration?: number;
  actionText?: string;
  onAction?: () => void;
}

interface ToastProps {
  toast: ToastItem;
  onRemove: (id: string) => void;
}

export function Toast({ toast, onRemove }: ToastProps) {
  useEffect(() => {
    if (toast.duration && toast.duration > 0) {
      const timer = setTimeout(() => {
        onRemove(toast.id);
      }, toast.duration);

      return () => clearTimeout(timer);
    }

    // duration이 없거나 0일 때도 cleanup 함수 반환
    return () => {
      // 정리할 것이 없지만 일관성을 위해 빈 함수 반환
    };
  }, [toast.id, toast.duration, onRemove]);

  const handleClose = () => {
    onRemove(toast.id);
  };

  const handleAction = () => {
    if (toast.onAction) {
      toast.onAction();
    }
    onRemove(toast.id);
  };

  return (
    <div className={`${styles.toast} ${styles[toast.type]}`} role='alert'>
      <div className={styles.content}>
        <div className={styles.header}>
          <h4 className={styles.title}>{toast.title}</h4>
          <button className={styles.closeButton} onClick={handleClose} aria-label='알림 닫기'>
            ×
          </button>
        </div>
        <p className={styles.message}>{toast.message}</p>
        {toast.actionText && toast.onAction && (
          <div className={styles.actions}>
            <button className={styles.actionButton} onClick={handleAction}>
              {toast.actionText}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// Global toast state
export const toasts = signal<ToastItem[]>([]);

let toastIdCounter = 0;

export function addToast(toast: Omit<ToastItem, 'id'>): string {
  const id = `toast_${++toastIdCounter}_${Date.now()}`;
  const newToast: ToastItem = {
    ...toast,
    id,
    duration: toast.duration ?? DEFAULT_TOAST_DURATION,
  };

  toasts.value = [...toasts.value, newToast];
  return id;
}

export function removeToast(id: string): void {
  toasts.value = toasts.value.filter(toast => toast.id !== id);
}

export function clearAllToasts(): void {
  toasts.value = [];
}
